/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import se.database.QueryMethods;
import se.model.Books;
import se.model.E_Books;

/**
 *
 * @author adde
 */
public class ViewBooks extends javax.swing.JFrame {
    
    private List<Books> books = new ArrayList<>();
    private List<E_Books> eBooks = new ArrayList<>();
    private QueryMethods queryMethods;

    /**
     * Creates new form ViewBooks
     */
    public ViewBooks() {
        initComponents();
        queryMethods = new QueryMethods();
        //books = queryMethods.getAllBooks();
        //eBooks = queryMethods.getAllEBooks();
    }
    
    public void sortBooksByTitle(List<Books> books){
        Collections.sort(books, (b1,b2) -> b1.getTitle().compareTo(b2.getTitle()));
     
    }
    
    public void sortBooksByTitleReverse(List<Books> books){
        Collections.sort(books, Collections.reverseOrder((b1,b2)-> b1.getTitle().compareTo(b2.getTitle())));
    }
    
    public void sortBooksByAuthor(List<Books> books){
        Collections.sort(books, (b1,b2) -> b1.getAuthor().compareTo(b2.getAuthor()));
    }
    
    public void sortBooksByAuthorReverse(List<Books> books){
        Collections.sort(books, Collections.reverseOrder((b1,b2)-> b1.getAuthor().compareTo(b2.getAuthor())));
    }
    
    public void sortBooksByCategory(List<Books> books){
        Collections.sort(books, (b1,b2) -> b1.getCategory().compareTo(b2.getCategory()));
    }
    
    public void sortBooksByCategoryReverse(List<Books> books){
        Collections.sort(books, Collections.reverseOrder((b1,b2) -> b1.getCategory().compareTo(b2.getCategory())));
    }
    
    public void sortBooksByPublisher(List<Books> books){
        Collections.sort(books, (b1,b2)-> b1.getPublisher().compareTo(b2.getPublisher()));
    }
    
    public void sortBooksByPublisherReverse(List<Books> books){
        Collections.sort(books, Collections.reverseOrder((b1,b2) -> b1.getPublisher().compareTo(b2.getPublisher())));
    }
    
    public void sortEBooksByTitle(List<E_Books> eBooks){
        Collections.sort(eBooks, (b1,b2) -> b1.getTitle().compareTo(b2.getTitle()));
     
    }
    
    public void sortEBooksByTitleReverse(List<E_Books> eBooks){
        Collections.sort(eBooks, Collections.reverseOrder((b1,b2)-> b1.getTitle().compareTo(b2.getTitle())));
    }
    
    public void sortEBooksByAuthor(List<E_Books> eBooks){
        Collections.sort(eBooks, (b1,b2) -> b1.getAuthor().compareTo(b2.getAuthor()));
    }
    
    public void sortEBooksByAuthorReverse(List<E_Books> eBooks){
        Collections.sort(eBooks, Collections.reverseOrder((b1,b2)-> b1.getAuthor().compareTo(b2.getAuthor())));
    }
    
    public void sortEBooksByCategory(List<E_Books> eBooks){
        Collections.sort(eBooks, (b1,b2) -> b1.getCategory().compareTo(b2.getCategory()));
    }
    
    public void sortEBooksByCategoryReverse(List<E_Books> eBooks){
        Collections.sort(eBooks, Collections.reverseOrder((b1,b2) -> b1.getCategory().compareTo(b2.getCategory())));
    }
    
    public void sortEBooksByPublisher(List<E_Books> eBooks){
        Collections.sort(eBooks, (b1,b2)-> b1.getPublisher().compareTo(b2.getPublisher()));
    }
    
    public void sortEBooksByPublisherReverse(List<E_Books> eBooks){
        Collections.sort(eBooks, Collections.reverseOrder((b1,b2) -> b1.getPublisher().compareTo(b2.getPublisher())));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
